eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8085/eureka
    server:
        waitTimeInMsWhenSyncEmpty: 0
logging:
    level:
        org:
            springframework:
                mail: DEBUG
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            expose: '*'
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: true

server:
    port: ${PORT:8092}
    servlet:
        context-path: /api
spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: 
        url: jdbc:h2:file:C:/DEV-KARTHI/CODEBASE/H2_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        #url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
        show-sql: true
